// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHSyL1oZkVJAFQbWUs3PtCB4znjVa4Eis',
    appId: '1:1054026255340:web:06ad045a8b8e3688b64ec9',
    messagingSenderId: '1054026255340',
    projectId: 'final-205f9',
    authDomain: 'final-205f9.firebaseapp.com',
    storageBucket: 'final-205f9.firebasestorage.app',
    measurementId: 'G-YR9N50FZ6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASlo1q_TVFEInelVzQoHZLbK1ImXwqbxM',
    appId: '1:1054026255340:android:3776b59aa1bd7307b64ec9',
    messagingSenderId: '1054026255340',
    projectId: 'final-205f9',
    storageBucket: 'final-205f9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHSyL1oZkVJAFQbWUs3PtCB4znjVa4Eis',
    appId: '1:1054026255340:web:e696010d012931b9b64ec9',
    messagingSenderId: '1054026255340',
    projectId: 'final-205f9',
    authDomain: 'final-205f9.firebaseapp.com',
    storageBucket: 'final-205f9.firebasestorage.app',
    measurementId: 'G-CWQBWQ9TPQ',
  );
}
